'$Dynamic
Screen _NewImage(640, 480, 32)
Type LoadedWord
    X As Integer
    Y As Integer
    Word As String
    Colour As Long
    Speed As Integer
End Type
Start:
Clear
Randomize Timer
Dim Shared Words$(1 To 3000)
Dim Shared MaxWords
Dim Shared LoadedWords(1 To 50) As LoadedWord
For I = 1 To 3000
    Read Words$(I)
Next I
Dim Shared Score As _Integer64, Money As _Integer64
Money = 100
Do
    Cls
    _Limit 60
    While _MouseInput: Wend
    Line (240, 96 * (_MouseY \ 96) + 30)-(400, 96 * (_MouseY \ 96) + 70), _RGB32(0, 127, 255), BF
    For I = 1 To 5
        If _MouseY \ 96 = I - 1 Then Color _RGB32(0, 255, 0), _RGB32(0, 127, 255) Else Color _RGB32(255), _RGB32(0)
        Select Case I
            Case 1: _PrintString (304, 40), "Easy"
            Case 2: _PrintString (296, 136), "Medium"
            Case 3: _PrintString (304, 232), "Hard"
            Case 4: _PrintString (292, 328), "Extreme"
            Case 5: _PrintString (280, 424), "Impossible"
        End Select
    Next I
    Color _RGB32(255), _RGB32(0)
    If _MouseButton(1) Then
        Select Case _MouseY \ 96
            Case 0: WordDelayTime = 4
                DifficultyCounter = 1
                MODE$ = "Easy"
            Case 1: WordDelayTime = 3
                DifficultyCounter = 2
                MODE$ = "Medium"
            Case 2: WordDelayTime = 2
                DifficultyCounter = 3
                MODE$ = "Hard"
            Case 3: WordDelayTime = 1
                DifficultyCounter = 4
                MODE$ = "Extreme"
            Case 4: WordDelayTime = 0.5
                DifficultyCounter = 5
                MODE$ = "Impossible"
        End Select
        Exit Do
    End If
    _Display
Loop
MaxWords = 50 - WordDelayTime * 10 - 5 * (WordDelayTime = 0.5)
KeyboardListenerTimer = _FreeTimer
On Timer(KeyboardListenerTimer, 0.001) GoSub KeyboardListener
Timer(KeyboardListenerTimer) On
NewWordTimer = _FreeTimer
On Timer(NewWordTimer, WordDelayTime) GoSub NewWord
Timer(NewWordTimer) On
GoSub NewWord
Color _RGB32(255), _RGB32(15)
LastWordTimer = Timer(0.1)
FPS = 10
Do
    Cls , _RGB32(15)
    _Limit FPS
    _KeyClear
    If _WindowHasFocus = 0 Then Paused = -1
    If Paused = 0 Then
        ClearInputWord = 0
        For I = 1 To MaxWords
            If Len(LoadedWords(I).Word) Then
                If PowerUp_Freeze = 0 Then LoadedWords(I).X = LoadedWords(I).X + LoadedWords(I).Speed / FPS
                Color LoadedWords(I).Colour, _RGB32(15)
                _PrintString (LoadedWords(I).X, LoadedWords(I).Y), LoadedWords(I).Word
                If LoadedWords(I).X + Len(LoadedWords(I).Word) * _FontWidth > 640 Then _PrintString (0, 16), "You Lose": _AutoDisplay: Exit Do
                If InStr(InputWord$, LoadedWords(I).Word) Then
                    Score = Score + Len(LoadedWords(I).Word) * (10 - Timer(0.1) + LastWordTimer) - (Len(InputWord$) - Len(LoadedWords(I).Word)) + LoadedWords(I).Speed + (_Width - LoadedWords(I).X - Len(LoadedWords(I).Word) * _FontWidth) * LoadedWords(I).Speed / _Width
                    Money = Money + Len(LoadedWords(I).Word) * (9 - WordDelayTime) / 4
                    LastWordTimer = Timer(0.1)
                    LoadedWords(I).Word = ""
                    ClearInputWord = -1
                    PauseTimer = 0
                End If
            End If
        Next I
        If ClearInputWord Then InputWord$ = ""
        If PowerUp_Freeze Then PowerUp_Freeze = PowerUp_Freeze - Sgn(PowerUp_Freeze)
    Else
        _AutoDisplay
        Line (_Width / 2 - 4 * _FontWidth, _Height / 2 - 3 * _FontHeight / 2)-(_Width / 2 + 4 * _FontWidth, _Height / 2 + 3 * _FontHeight / 2), _RGB32(127), BF
        Color _RGB32(255), _RGB32(127): _PrintString (_Width / 2 - 3 * _FontWidth, _Height / 2 - _FontHeight / 2), "Paused"
        PauseTimer = Timer(0.1)
        Timer(KeyboardListenerTimer) Off
        Timer(NewWordTimer) Off
        'Do While _KeyDown(100306) and (_KeyDown(80) Or _KeyDown(112)): Loop
        Sleep
        Timer(KeyboardListenerTimer) On
        Timer(NewWordTimer) On
        LastWordTimer = Timer(0.1) - PauseTimer + LastWordTimer
        Paused = 0
    End If
    If InputWord$ = "exit" + Chr$(13) Then System
    Color _RGB32(255), _RGB32(15)
    _PrintString (0, 464), "Word: " + InputWord$
    _PrintString (0, 0), "Score: " + _Trim$(Str$(Score))
    _PrintString (592 - 8 * Len(MODE$), 0), "Mode: " + MODE$
    _PrintString (320, 0), "Money: " + _Trim$(Str$(Money))
    _Display
Loop
Timer(KeyboardListenerTimer) Free
Timer(NewWordTimer) Free
Do
    If InKey$ = Chr$(13) Then Exit Do
Loop
GoTo Start
System
KeyboardListener:
If (_KeyDown(100306) = -1 And (_KeyDown(80) = -1 Or _KeyDown(112) = -1)) Then Paused = -1: Return
Key$ = InKey$
If Key$ = Chr$(8) Then
    If Money > 5 Then
        InputWord$ = Left$(InputWord$, Len(InputWord$) - 1)
        Money = Money - 5
    End If
ElseIf Key$ = "[" Then
    If Money > 500 * DifficultyCounter Then
        For I = 1 To 4 * (WordDelayTime + 1)
            LoadedWords(GetMax_OffsetX).Word = ""
        Next I
        Money = Money - 500
        Score = Score + I + 500
    End If
ElseIf Key$ = "]" Then
    If Money > 250 * DifficultyCounter Then
        PowerUp_Freeze = FPS * 5
        Money = Money - 250
        Score = Score + 250
    End If
ElseIf Key$ = "\" Then
    If Money > 100 * DifficultyCounter Then
        W$ = LoadedWords(GetMin_Length).Word
        For I = 1 To 3 * (WordDelayTime + 1) + 1
            LoadedWords(GetMax_OffsetX).Word = W$
        Next I
        Money = Money - 100
        Score = Score + 100
    End If
Else
    If Len(Key$) = 1 Then
        If Asc(Key$) = 13 Or (Asc(Key$) >= 65 And Asc(Key$) <= 122) Or Asc(Key$) = 45 Then InputWord$ = InputWord$ + Key$
    End If
End If
Return
NewWord:
ID = Int(Rnd * 3000) + 1
LW = 0
For I = 1 To MaxWords
    If Len(LoadedWords(I).Word) = 0 Then LW = I: Exit For
Next I
If LW > 0 Then
    LoadedWords(LW).X = 1
    LoadedWords(LW).Y = Int(Rnd * (_Height - 32) / 16) * 16 + 16
    LoadedWords(LW).Word = LCase$(Words$(ID))
    LoadedWords(LW).Colour = _RGB32(128 + Rnd * 128, 128 + Rnd * 128, 128 + Rnd * 128)
    If Len(LoadedWords(LW).Word) <= 5 And Rnd < 0.05 Then LoadedWords(LW).Speed = 20 Else LoadedWords(LW).Speed = 10
End If
Return
Data a
Data abandon
Data ability
Data able
Data abortion
Data about
Data above
Data abroad
Data absence
Data absolute
Data absolutely
Data absorb
Data abuse
Data academic
Data accept
Data access
Data accident
Data accompany
Data accomplish
Data according
Data account
Data accurate
Data accuse
Data achieve
Data achievement
Data acid
Data acknowledge
Data acquire
Data across
Data act
Data action
Data active
Data activist
Data activity
Data actor
Data actress
Data actual
Data actually
Data ad
Data adapt
Data add
Data addition
Data additional
Data address
Data adequate
Data adjust
Data adjustment
Data administration
Data administrator
Data admire
Data admission
Data admit
Data adolescent
Data adopt
Data adult
Data advance
Data advanced
Data advantage
Data adventure
Data advertising
Data advice
Data advise
Data adviser
Data advocate
Data affair
Data affect
Data afford
Data afraid
Data African
Data African-American
Data after
Data afternoon
Data again
Data against
Data age
Data agency
Data agenda
Data agent
Data aggressive
Data ago
Data agree
Data agreement
Data agricultural
Data ah
Data ahead
Data aid
Data aide
Data AIDS
Data aim
Data air
Data aircraft
Data airline
Data airport
Data album
Data alcohol
Data alive
Data all
Data alliance
Data allow
Data ally
Data almost
Data alone
Data along
Data already
Data also
Data alter
Data alternative
Data although
Data always
Data AM
Data amazing
Data American
Data among
Data amount
Data analysis
Data analyst
Data analyze
Data ancient
Data and
Data anger
Data angle
Data angry
Data animal
Data anniversary
Data announce
Data annual
Data another
Data answer
Data anticipate
Data anxiety
Data any
Data anybody
Data anymore
Data anyone
Data anything
Data anyway
Data anywhere
Data apart
Data apartment
Data apparent
Data apparently
Data appeal
Data appear
Data appearance
Data apple
Data application
Data apply
Data appoint
Data appointment
Data appreciate
Data approach
Data appropriate
Data approval
Data approve
Data approximately
Data Arab
Data architect
Data area
Data argue
Data argument
Data arise
Data arm
Data armed
Data army
Data around
Data arrange
Data arrangement
Data arrest
Data arrival
Data arrive
Data art
Data article
Data artist
Data artistic
Data as
Data Asian
Data aside
Data ask
Data asleep
Data aspect
Data assault
Data assert
Data assess
Data assessment
Data asset
Data assign
Data assignment
Data assist
Data assistance
Data assistant
Data associate
Data association
Data assume
Data assumption
Data assure
Data at
Data athlete
Data athletic
Data atmosphere
Data attach
Data attack
Data attempt
Data attend
Data attention
Data attitude
Data attorney
Data attract
Data attractive
Data attribute
Data audience
Data author
Data authority
Data auto
Data available
Data average
Data avoid
Data award
Data aware
Data awareness
Data away
Data awful
Data baby
Data back
Data background
Data bad
Data badly
Data bag
Data bake
Data balance
Data ball
Data ban
Data band
Data bank
Data bar
Data barely
Data barrel
Data barrier
Data base
Data baseball
Data basic
Data basically
Data basis
Data basket
Data basketball
Data bathroom
Data battery
Data battle
Data be
Data beach
Data bean
Data bear
Data beat
Data beautiful
Data beauty
Data because
Data become
Data bed
Data bedroom
Data beer
Data before
Data begin
Data beginning
Data behavior
Data behind
Data being
Data belief
Data believe
Data bell
Data belong
Data below
Data belt
Data bench
Data bend
Data beneath
Data benefit
Data beside
Data besides
Data best
Data bet
Data better
Data between
Data beyond
Data Bible
Data big
Data bike
Data bill
Data billion
Data bind
Data biological
Data bird
Data birth
Data birthday
Data bit
Data bite
Data black
Data blade
Data blame
Data blanket
Data blind
Data block
Data blood
Data blow
Data blue
Data board
Data boat
Data body
Data bomb
Data bombing
Data bond
Data bone
Data book
Data boom
Data boot
Data border
Data born
Data borrow
Data boss
Data both
Data bother
Data bottle
Data bottom
Data boundary
Data bowl
Data box
Data boy
Data boyfriend
Data brain
Data branch
Data brand
Data bread
Data break
Data breakfast
Data breast
Data breath
Data breathe
Data brick
Data bridge
Data brief
Data briefly
Data bright
Data brilliant
Data bring
Data British
Data broad
Data broken
Data brother
Data brown
Data brush
Data buck
Data budget
Data build
Data building
Data bullet
Data bunch
Data burden
Data burn
Data bury
Data bus
Data business
Data busy
Data but
Data butter
Data button
Data buy
Data buyer
Data by
Data cabin
Data cabinet
Data cable
Data cake
Data calculate
Data call
Data camera
Data camp
Data campaign
Data campus
Data can
Data Canadian
Data cancer
Data candidate
Data cap
Data capability
Data capable
Data capacity
Data capital
Data captain
Data capture
Data car
Data carbon
Data card
Data care
Data career
Data careful
Data carefully
Data carrier
Data carry
Data case
Data cash
Data cast
Data cat
Data catch
Data category
Data Catholic
Data cause
Data ceiling
Data celebrate
Data celebration
Data celebrity
Data cell
Data center
Data central
Data century
Data CEO
Data ceremony
Data certain
Data certainly
Data chain
Data chair
Data chairman
Data challenge
Data chamber
Data champion
Data championship
Data chance
Data change
Data changing
Data channel
Data chapter
Data character
Data characteristic
Data characterize
Data charge
Data charity
Data chart
Data chase
Data cheap
Data check
Data cheek
Data cheese
Data chef
Data chemical
Data chest
Data chicken
Data chief
Data child
Data childhood
Data Chinese
Data chip
Data chocolate
Data choice
Data cholesterol
Data choose
Data Christian
Data Christmas
Data church
Data cigarette
Data circle
Data circumstance
Data cite
Data citizen
Data city
Data civil
Data civilian
Data claim
Data class
Data classic
Data classroom
Data clean
Data clear
Data clearly
Data client
Data climate
Data climb
Data clinic
Data clinical
Data clock
Data close
Data closely
Data closer
Data clothes
Data clothing
Data cloud
Data club
Data clue
Data cluster
Data coach
Data coal
Data coalition
Data coast
Data coat
Data code
Data coffee
Data cognitive
Data cold
Data collapse
Data colleague
Data collect
Data collection
Data collective
Data college
Data colonial
Data color
Data column
Data combination
Data combine
Data come
Data comedy
Data comfort
Data comfortable
Data command
Data commander
Data comment
Data commercial
Data commission
Data commit
Data commitment
Data committee
Data common
Data communicate
Data communication
Data community
Data company
Data compare
Data comparison
Data compete
Data competition
Data competitive
Data competitor
Data complain
Data complaint
Data complete
Data completely
Data complex
Data complicated
Data component
Data compose
Data composition
Data comprehensive
Data computer
Data concentrate
Data concentration
Data concept
Data concern
Data concerned
Data concert
Data conclude
Data conclusion
Data concrete
Data condition
Data conduct
Data conference
Data confidence
Data confident
Data confirm
Data conflict
Data confront
Data confusion
Data Congress
Data congressional
Data connect
Data connection
Data consciousness
Data consensus
Data consequence
Data conservative
Data consider
Data considerable
Data consideration
Data consist
Data consistent
Data constant
Data constantly
Data constitute
Data constitutional
Data construct
Data construction
Data consultant
Data consume
Data consumer
Data consumption
Data contact
Data contain
Data container
Data contemporary
Data content
Data contest
Data context
Data continue
Data continued
Data contract
Data contrast
Data contribute
Data contribution
Data control
Data controversial
Data controversy
Data convention
Data conventional
Data conversation
Data convert
Data conviction
Data convince
Data cook
Data cookie
Data cooking
Data cool
Data cooperation
Data cop
Data cope
Data copy
Data core
Data corn
Data corner
Data corporate
Data corporation
Data correct
Data correspondent
Data cost
Data cotton
Data couch
Data could
Data council
Data counselor
Data count
Data counter
Data country
Data county
Data couple
Data courage
Data course
Data court
Data cousin
Data cover
Data coverage
Data cow
Data crack
Data craft
Data crash
Data crazy
Data cream
Data create
Data creation
Data creative
Data creature
Data credit
Data crew
Data crime
Data criminal
Data crisis
Data criteria
Data critic
Data critical
Data criticism
Data criticize
Data crop
Data cross
Data crowd
Data crucial
Data cry
Data cultural
Data culture
Data cup
Data curious
Data current
Data currently
Data curriculum
Data custom
Data customer
Data cut
Data cycle
Data dad
Data daily
Data damage
Data dance
Data danger
Data dangerous
Data dare
Data dark
Data darkness
Data data
Data date
Data daughter
Data day
Data dead
Data deal
Data dealer
Data dear
Data death
Data debate
Data debt
Data decade
Data decide
Data decision
Data deck
Data declare
Data decline
Data decrease
Data deep
Data deeply
Data deer
Data defeat
Data defend
Data defendant
Data defense
Data defensive
Data deficit
Data define
Data definitely
Data definition
Data degree
Data delay
Data deliver
Data delivery
Data demand
Data democracy
Data Democrat
Data democratic
Data demonstrate
Data demonstration
Data deny
Data department
Data depend
Data dependent
Data depending
Data depict
Data depression
Data depth
Data deputy
Data derive
Data describe
Data description
Data desert
Data deserve
Data design
Data designer
Data desire
Data desk
Data desperate
Data despite
Data destroy
Data destruction
Data detail
Data detailed
Data detect
Data determine
Data develop
Data developing
Data development
Data device
Data devote
Data dialogue
Data die
Data diet
Data differ
Data difference
Data different
Data differently
Data difficult
Data difficulty
Data dig
Data digital
Data dimension
Data dining
Data dinner
Data direct
Data direction
Data directly
Data director
Data dirt
Data dirty
Data disability
Data disagree
Data disappear
Data disaster
Data discipline
Data discourse
Data discover
Data discovery
Data discrimination
Data discuss
Data discussion
Data disease
Data dish
Data dismiss
Data disorder
Data display
Data dispute
Data distance
Data distant
Data distinct
Data distinction
Data distinguish
Data distribute
Data distribution
Data district
Data diverse
Data diversity
Data divide
Data division
Data divorce
Data DNA
Data do
Data doctor
Data document
Data dog
Data domestic
Data dominant
Data dominate
Data door
Data double
Data doubt
Data down
Data downtown
Data dozen
Data draft
Data drag
Data drama
Data dramatic
Data dramatically
Data draw
Data drawing
Data dream
Data dress
Data drink
Data drive
Data driver
Data drop
Data drug
Data dry
Data due
Data during
Data dust
Data duty
Data each
Data eager
Data ear
Data early
Data earn
Data earnings
Data earth
Data ease
Data easily
Data east
Data eastern
Data easy
Data eat
Data economic
Data economics
Data economist
Data economy
Data edge
Data edition
Data editor
Data educate
Data education
Data educational
Data educator
Data effect
Data effective
Data effectively
Data efficiency
Data efficient
Data effort
Data egg
Data eight
Data either
Data elderly
Data elect
Data election
Data electric
Data electricity
Data electronic
Data element
Data elementary
Data eliminate
Data elite
Data else
Data elsewhere
Data e-mail
Data embrace
Data emerge
Data emergency
Data emission
Data emotion
Data emotional
Data emphasis
Data emphasize
Data employ
Data employee
Data employer
Data employment
Data empty
Data enable
Data encounter
Data encourage
Data end
Data enemy
Data energy
Data enforcement
Data engage
Data engine
Data engineer
Data engineering
Data English
Data enhance
Data enjoy
Data enormous
Data enough
Data ensure
Data enter
Data enterprise
Data entertainment
Data entire
Data entirely
Data entrance
Data entry
Data environment
Data environmental
Data episode
Data equal
Data equally
Data equipment
Data era
Data error
Data escape
Data especially
Data essay
Data essential
Data essentially
Data establish
Data establishment
Data estate
Data estimate
Data etc
Data ethics
Data ethnic
Data European
Data evaluate
Data evaluation
Data even
Data evening
Data event
Data eventually
Data ever
Data every
Data everybody
Data everyday
Data everyone
Data everything
Data everywhere
Data evidence
Data evolution
Data evolve
Data exact
Data exactly
Data examination
Data examine
Data example
Data exceed
Data excellent
Data except
Data exception
Data exchange
Data exciting
Data executive
Data exercise
Data exhibit
Data exhibition
Data exist
Data existence
Data existing
Data expand
Data expansion
Data expect
Data expectation
Data expense
Data expensive
Data experience
Data experiment
Data expert
Data explain
Data explanation
Data explode
Data explore
Data explosion
Data expose
Data exposure
Data express
Data expression
Data extend
Data extension
Data extensive
Data extent
Data external
Data extra
Data extraordinary
Data extreme
Data extremely
Data eye
Data fabric
Data face
Data facility
Data fact
Data factor
Data factory
Data faculty
Data fade
Data fail
Data failure
Data fair
Data fairly
Data faith
Data fall
Data false
Data familiar
Data family
Data famous
Data fan
Data fantasy
Data far
Data farm
Data farmer
Data fashion
Data fast
Data fat
Data fate
Data father
Data fault
Data favor
Data favorite
Data fear
Data feature
Data federal
Data fee
Data feed
Data feel
Data feeling
Data fellow
Data female
Data fence
Data few
Data fewer
Data fiber
Data fiction
Data field
Data fifteen
Data fifth
Data fifty
Data fight
Data fighter
Data fighting
Data figure
Data file
Data fill
Data film
Data final
Data finally
Data finance
Data financial
Data find
Data finding
Data fine
Data finger
Data finish
Data fire
Data firm
Data first
Data fish
Data fishing
Data fit
Data fitness
Data five
Data fix
Data flag
Data flame
Data flat
Data flavor
Data flee
Data flesh
Data flight
Data float
Data floor
Data flow
Data flower
Data fly
Data focus
Data folk
Data follow
Data following
Data food
Data foot
Data football
Data for
Data force
Data foreign
Data forest
Data forever
Data forget
Data form
Data formal
Data formation
Data former
Data formula
Data forth
Data fortune
Data forward
Data found
Data foundation
Data founder
Data four
Data fourth
Data frame
Data framework
Data free
Data freedom
Data freeze
Data French
Data frequency
Data frequent
Data frequently
Data fresh
Data friend
Data friendly
Data friendship
Data from
Data front
Data fruit
Data frustration
Data fuel
Data full
Data fully
Data fun
Data function
Data fund
Data fundamental
Data funding
Data funeral
Data funny
Data furniture
Data furthermore
Data future
Data gain
Data galaxy
Data gallery
Data game
Data gang
Data gap
Data garage
Data garden
Data garlic
Data gas
Data gate
Data gather
Data gay
Data gaze
Data gear
Data gender
Data gene
Data general
Data generally
Data generate
Data generation
Data genetic
Data gentleman
Data gently
Data German
Data gesture
Data get
Data ghost
Data giant
Data gift
Data gifted
Data girl
Data girlfriend
Data give
Data given
Data glad
Data glance
Data glass
Data global
Data glove
Data go
Data goal
Data God
Data gold
Data golden
Data golf
Data good
Data government
Data governor
Data grab
Data grade
Data gradually
Data graduate
Data grain
Data grand
Data grandfather
Data grandmother
Data grant
Data grass
Data grave
Data gray
Data great
Data greatest
Data green
Data grocery
Data ground
Data group
Data grow
Data growing
Data growth
Data guarantee
Data guard
Data guess
Data guest
Data guide
Data guideline
Data guilty
Data gun
Data guy
Data habit
Data habitat
Data hair
Data half
Data hall
Data hand
Data handful
Data handle
Data hang
Data happen
Data happy
Data hard
Data hardly
Data hat
Data hate
Data have
Data he
Data head
Data headline
Data headquarters
Data health
Data healthy
Data hear
Data hearing
Data heart
Data heat
Data heaven
Data heavily
Data heavy
Data heel
Data height
Data helicopter
Data hell
Data hello
Data help
Data helpful
Data her
Data here
Data heritage
Data hero
Data herself
Data hey
Data hi
Data hide
Data high
Data highlight
Data highly
Data highway
Data hill
Data him
Data himself
Data hip
Data hire
Data his
Data historian
Data historic
Data historical
Data history
Data hit
Data hold
Data hole
Data holiday
Data holy
Data home
Data homeless
Data honest
Data honey
Data honor
Data hope
Data horizon
Data horror
Data horse
Data hospital
Data host
Data hot
Data hotel
Data hour
Data house
Data household
Data housing
Data how
Data however
Data huge
Data human
Data humor
Data hundred
Data hungry
Data hunter
Data hunting
Data hurt
Data husband
Data hypothesis
Data I
Data ice
Data idea
Data ideal
Data identification
Data identify
Data identity
Data ie
Data if
Data ignore
Data ill
Data illegal
Data illness
Data illustrate
Data image
Data imagination
Data imagine
Data immediate
Data immediately
Data immigrant
Data immigration
Data impact
Data implement
Data implication
Data imply
Data importance
Data important
Data impose
Data impossible
Data impress
Data impression
Data impressive
Data improve
Data improvement
Data in
Data incentive
Data incident
Data include
Data including
Data income
Data incorporate
Data increase
Data increased
Data increasing
Data increasingly
Data incredible
Data indeed
Data independence
Data independent
Data index
Data Indian
Data indicate
Data indication
Data individual
Data industrial
Data industry
Data infant
Data infection
Data inflation
Data influence
Data inform
Data information
Data ingredient
Data initial
Data initially
Data initiative
Data injury
Data inner
Data innocent
Data inquiry
Data inside
Data insight
Data insist
Data inspire
Data install
Data instance
Data instead
Data institution
Data institutional
Data instruction
Data instructor
Data instrument
Data insurance
Data intellectual
Data intelligence
Data intend
Data intense
Data intensity
Data intention
Data interaction
Data interest
Data interested
Data interesting
Data internal
Data international
Data Internet
Data interpret
Data interpretation
Data intervention
Data interview
Data into
Data introduce
Data introduction
Data invasion
Data invest
Data investigate
Data investigation
Data investigator
Data investment
Data investor
Data invite
Data involve
Data involved
Data involvement
Data Iraqi
Data Irish
Data iron
Data Islamic
Data island
Data Israeli
Data issue
Data it
Data Italian
Data item
Data its
Data itself
Data jacket
Data jail
Data Japanese
Data jet
Data Jew
Data Jewish
Data job
Data join
Data joint
Data joke
Data journal
Data journalist
Data journey
Data joy
Data judge
Data judgment
Data juice
Data jump
Data junior
Data jury
Data just
Data justice
Data justify
Data keep
Data key
Data kick
Data kid
Data kill
Data killer
Data killing
Data kind
Data king
Data kiss
Data kitchen
Data knee
Data knife
Data knock
Data know
Data knowledge
Data lab
Data label
Data labor
Data laboratory
Data lack
Data lady
Data lake
Data land
Data landscape
Data language
Data lap
Data large
Data largely
Data last
Data late
Data later
Data Latin
Data latter
Data laugh
Data launch
Data law
Data lawn
Data lawsuit
Data lawyer
Data lay
Data layer
Data lead
Data leader
Data leadership
Data leading
Data leaf
Data league
Data lean
Data learn
Data learning
Data least
Data leather
Data leave
Data left
Data leg
Data legacy
Data legal
Data legend
Data legislation
Data legitimate
Data lemon
Data length
Data less
Data lesson
Data let
Data letter
Data level
Data liberal
Data library
Data license
Data lie
Data life
Data lifestyle
Data lifetime
Data lift
Data light
Data like
Data likely
Data limit
Data limitation
Data limited
Data line
Data link
Data lip
Data list
Data listen
Data literally
Data literary
Data literature
Data little
Data live
Data living
Data load
Data loan
Data local
Data locate
Data location
Data lock
Data long
Data long-term
Data look
Data loose
Data lose
Data loss
Data lost
Data lot
Data lots
Data loud
Data love
Data lovely
Data lover
Data low
Data lower
Data luck
Data lucky
Data lunch
Data lung
Data machine
Data mad
Data magazine
Data mail
Data main
Data mainly
Data maintain
Data maintenance
Data major
Data majority
Data make
Data maker
Data makeup
Data male
Data mall
Data man
Data manage
Data management
Data manager
Data manner
Data manufacturer
Data manufacturing
Data many
Data map
Data margin
Data mark
Data market
Data marketing
Data marriage
Data married
Data marry
Data mask
Data mass
Data massive
Data master
Data match
Data material
Data math
Data matter
Data may
Data maybe
Data mayor
Data me
Data meal
Data mean
Data meaning
Data meanwhile
Data measure
Data measurement
Data meat
Data mechanism
Data media
Data medical
Data medication
Data medicine
Data medium
Data meet
Data meeting
Data member
Data membership
Data memory
Data mental
Data mention
Data menu
Data mere
Data merely
Data mess
Data message
Data metal
Data meter
Data method
Data Mexican
Data middle
Data might
Data military
Data milk
Data million
Data mind
Data mine
Data minister
Data minor
Data minority
Data minute
Data miracle
Data mirror
Data miss
Data missile
Data mission
Data mistake
Data mix
Data mixture
Data mm-hmm
Data mode
Data model
Data moderate
Data modern
Data modest
Data mom
Data moment
Data money
Data monitor
Data month
Data mood
Data moon
Data moral
Data more
Data moreover
Data morning
Data mortgage
Data most
Data mostly
Data mother
Data motion
Data motivation
Data motor
Data mount
Data mountain
Data mouse
Data mouth
Data move
Data movement
Data movie
Data Mr
Data Mrs
Data Ms
Data much
Data multiple
Data murder
Data muscle
Data museum
Data music
Data musical
Data musician
Data Muslim
Data must
Data mutual
Data my
Data myself
Data mystery
Data myth
Data naked
Data name
Data narrative
Data narrow
Data nation
Data national
Data native
Data natural
Data naturally
Data nature
Data near
Data nearby
Data nearly
Data necessarily
Data necessary
Data neck
Data need
Data negative
Data negotiate
Data negotiation
Data neighbor
Data neighborhood
Data neither
Data nerve
Data nervous
Data net
Data network
Data never
Data nevertheless
Data new
Data newly
Data news
Data newspaper
Data next
Data nice
Data night
Data nine
Data no
Data nobody
Data nod
Data noise
Data nomination
Data none
Data nonetheless
Data nor
Data normal
Data normally
Data north
Data northern
Data nose
Data not
Data note
Data nothing
Data notice
Data notion
Data novel
Data now
Data nowhere
Data n't
Data nuclear
Data number
Data numerous
Data nurse
Data nut
Data object
Data objective
Data obligation
Data observation
Data observe
Data observer
Data obtain
Data obvious
Data obviously
Data occasion
Data occasionally
Data occupation
Data occupy
Data occur
Data ocean
Data odd
Data odds
Data of
Data off
Data offense
Data offensive
Data offer
Data office
Data officer
Data official
Data often
Data oh
Data oil
Data ok
Data okay
Data old
Data Olympic
Data on
Data once
Data one
Data ongoing
Data onion
Data online
Data only
Data onto
Data open
Data opening
Data operate
Data operating
Data operation
Data operator
Data opinion
Data opponent
Data opportunity
Data oppose
Data opposite
Data opposition
Data option
Data or
Data orange
Data order
Data ordinary
Data organic
Data organization
Data organize
Data orientation
Data origin
Data original
Data originally
Data other
Data others
Data otherwise
Data ought
Data our
Data ourselves
Data out
Data outcome
Data outside
Data oven
Data over
Data overall
Data overcome
Data overlook
Data owe
Data own
Data owner
Data pace
Data pack
Data package
Data page
Data pain
Data painful
Data paint
Data painter
Data painting
Data pair
Data pale
Data Palestinian
Data palm
Data pan
Data panel
Data pant
Data paper
Data parent
Data park
Data parking
Data part
Data participant
Data participate
Data participation
Data particular
Data particularly
Data partly
Data partner
Data partnership
Data party
Data pass
Data passage
Data passenger
Data passion
Data past
Data patch
Data path
Data patient
Data pattern
Data pause
Data pay
Data payment
Data PC
Data peace
Data peak
Data peer
Data penalty
Data people
Data pepper
Data per
Data perceive
Data percentage
Data perception
Data perfect
Data perfectly
Data perform
Data performance
Data perhaps
Data period
Data permanent
Data permission
Data permit
Data person
Data personal
Data personality
Data personally
Data personnel
Data perspective
Data persuade
Data pet
Data phase
Data phenomenon
Data philosophy
Data phone
Data photo
Data photograph
Data photographer
Data phrase
Data physical
Data physically
Data physician
Data piano
Data pick
Data picture
Data pie
Data piece
Data pile
Data pilot
Data pine
Data pink
Data pipe
Data pitch
Data place
Data plan
Data plane
Data planet
Data planning
Data plant
Data plastic
Data plate
Data platform
Data play
Data player
Data please
Data pleasure
Data plenty
Data plot
Data plus
Data PM
Data pocket
Data poem
Data poet
Data poetry
Data point
Data pole
Data police
Data policy
Data political
Data politically
Data politician
Data politics
Data poll
Data pollution
Data pool
Data poor
Data pop
Data popular
Data population
Data porch
Data port
Data portion
Data portrait
Data portray
Data pose
Data position
Data positive
Data possess
Data possibility
Data possible
Data possibly
Data post
Data pot
Data potato
Data potential
Data potentially
Data pound
Data pour
Data poverty
Data powder
Data power
Data powerful
Data practical
Data practice
Data pray
Data prayer
Data precisely
Data predict
Data prefer
Data preference
Data pregnancy
Data pregnant
Data preparation
Data prepare
Data prescription
Data presence
Data present
Data presentation
Data preserve
Data president
Data presidential
Data press
Data pressure
Data pretend
Data pretty
Data prevent
Data previous
Data previously
Data price
Data pride
Data priest
Data primarily
Data primary
Data prime
Data principal
Data principle
Data print
Data prior
Data priority
Data prison
Data prisoner
Data privacy
Data private
Data probably
Data problem
Data procedure
Data proceed
Data process
Data produce
Data producer
Data product
Data production
Data profession
Data professional
Data professor
Data profile
Data profit
Data program
Data progress
Data project
Data prominent
Data promise
Data promote
Data prompt
Data proof
Data proper
Data properly
Data property
Data proportion
Data proposal
Data propose
Data proposed
Data prosecutor
Data prospect
Data protect
Data protection
Data protein
Data protest
Data proud
Data prove
Data provide
Data provider
Data province
Data provision
Data psychological
Data psychologist
Data psychology
Data public
Data publication
Data publicly
Data publish
Data publisher
Data pull
Data punishment
Data purchase
Data pure
Data purpose
Data pursue
Data push
Data put
Data qualify
Data quality
Data quarter
Data quarterback
Data question
Data quick
Data quickly
Data quiet
Data quietly
Data quit
Data quite
Data quote
Data race
Data racial
Data radical
Data radio
Data rail
Data rain
Data raise
Data range
Data rank
Data rapid
Data rapidly
Data rare
Data rarely
Data rate
Data rather
Data rating
Data ratio
Data raw
Data reach
Data react
Data reaction
Data read
Data reader
Data reading
Data ready
Data real
Data reality
Data realize
Data really
Data reason
Data reasonable
Data recall
Data receive
Data recent
Data recently
Data recipe
Data recognition
Data recognize
Data recommend
Data recommendation
Data record
Data recording
Data recover
Data recovery
Data recruit
Data red
Data reduce
Data reduction
Data refer
Data reference
Data reflect
Data reflection
Data reform
Data refugee
Data refuse
Data regard
Data regarding
Data regardless
Data regime
Data region
Data regional
Data register
Data regular
Data regularly
Data regulate
Data regulation
Data reinforce
Data reject
Data relate
Data relation
Data relationship
Data relative
Data relatively
Data relax
Data release
Data relevant
Data relief
Data religion
Data religious
Data rely
Data remain
Data remaining
Data remarkable
Data remember
Data remind
Data remote
Data remove
Data repeat
Data repeatedly
Data replace
Data reply
Data report
Data reporter
Data represent
Data representation
Data representative
Data Republican
Data reputation
Data request
Data require
Data requirement
Data research
Data researcher
Data resemble
Data reservation
Data resident
Data resist
Data resistance
Data resolution
Data resolve
Data resort
Data resource
Data respect
Data respond
Data respondent
Data response
Data responsibility
Data responsible
Data rest
Data restaurant
Data restore
Data restriction
Data result
Data retain
Data retire
Data retirement
Data return
Data reveal
Data revenue
Data review
Data revolution
Data rhythm
Data rice
Data rich
Data rid
Data ride
Data rifle
Data right
Data ring
Data rise
Data risk
Data river
Data road
Data rock
Data role
Data roll
Data romantic
Data roof
Data room
Data root
Data rope
Data rose
Data rough
Data roughly
Data round
Data route
Data routine
Data row
Data rub
Data rule
Data run
Data running
Data rural
Data rush
Data Russian
Data sacred
Data sad
Data safe
Data safety
Data sake
Data salad
Data salary
Data sale
Data sales
Data salt
Data same
Data sample
Data sanction
Data sand
Data satellite
Data satisfaction
Data satisfy
Data sauce
Data save
Data saving
Data say
Data scale
Data scandal
Data scared
Data scenario
Data scene
Data schedule
Data scheme
Data scholar
Data scholarship
Data school
Data science
Data scientific
Data scientist
Data scope
Data score
Data scream
Data screen
Data script
Data sea
Data search
Data season
Data seat
Data second
Data secret
Data secretary
Data section
Data sector
Data secure
Data security
Data see
Data seed
Data seek
Data seem
Data segment
Data seize
Data select
Data selection
Data self
Data sell
Data Senate
Data senator
Data send
Data senior
Data sense
Data sensitive
Data sentence
Data separate
Data sequence
Data series
Data serious
Data seriously
Data serve
Data service
Data session
Data set
Data setting
Data settle
Data settlement
Data seven
Data several
Data severe
Data sex
Data sexual
Data shade
Data shadow
Data shake
Data shall
Data shape
Data share
Data sharp
Data she
Data sheet
Data shelf
Data shell
Data shelter
Data shift
Data shine
Data ship
Data shirt
Data shit
Data shock
Data shoe
Data shoot
Data shooting
Data shop
Data shopping
Data shore
Data short
Data shortly
Data shot
Data should
Data shoulder
Data shout
Data show
Data shower
Data shrug
Data shut
Data sick
Data side
Data sigh
Data sight
Data sign
Data signal
Data significance
Data significant
Data significantly
Data silence
Data silent
Data silver
Data similar
Data similarly
Data simple
Data simply
Data sin
Data since
Data sing
Data singer
Data single
Data sink
Data sir
Data sister
Data sit
Data site
Data situation
Data six
Data size
Data ski
Data skill
Data skin
Data sky
Data slave
Data sleep
Data slice
Data slide
Data slight
Data slightly
Data slip
Data slow
Data slowly
Data small
Data smart
Data smell
Data smile
Data smoke
Data smooth
Data snap
Data snow
Data so
Data so-called
Data soccer
Data social
Data society
Data soft
Data software
Data soil
Data solar
Data soldier
Data solid
Data solution
Data solve
Data some
Data somebody
Data somehow
Data someone
Data something
Data sometimes
Data somewhat
Data somewhere
Data son
Data song
Data soon
Data sophisticated
Data sorry
Data sort
Data soul
Data sound
Data soup
Data source
Data south
Data southern
Data Soviet
Data space
Data Spanish
Data speak
Data speaker
Data special
Data specialist
Data species
Data specific
Data specifically
Data speech
Data speed
Data spend
Data spending
Data spin
Data spirit
Data spiritual
Data split
Data spokesman
Data sport
Data spot
Data spread
Data spring
Data square
Data squeeze
Data stability
Data stable
Data staff
Data stage
Data stair
Data stake
Data stand
Data standard
Data standing
Data star
Data stare
Data start
Data state
Data statement
Data station
Data statistics
Data status
Data stay
Data steady
Data steal
Data steel
Data step
Data stick
Data still
Data stir
Data stock
Data stomach
Data stone
Data stop
Data storage
Data store
Data storm
Data story
Data straight
Data strange
Data stranger
Data strategic
Data strategy
Data stream
Data street
Data strength
Data strengthen
Data stress
Data stretch
Data strike
Data string
Data strip
Data stroke
Data strong
Data strongly
Data structure
Data struggle
Data student
Data studio
Data study
Data stuff
Data stupid
Data style
Data subject
Data submit
Data subsequent
Data substance
Data substantial
Data succeed
Data success
Data successful
Data successfully
Data such
Data sudden
Data suddenly
Data sue
Data suffer
Data sufficient
Data sugar
Data suggest
Data suggestion
Data suicide
Data suit
Data summer
Data summit
Data sun
Data super
Data supply
Data support
Data supporter
Data suppose
Data supposed
Data Supreme
Data sure
Data surely
Data surface
Data surgery
Data surprise
Data surprised
Data surprising
Data surprisingly
Data surround
Data survey
Data survival
Data survive
Data survivor
Data suspect
Data sustain
Data swear
Data sweep
Data sweet
Data swim
Data swing
Data switch
Data symbol
Data symptom
Data system
Data table
Data tablespoon
Data tactic
Data tail
Data take
Data tale
Data talent
Data talk
Data tall
Data tank
Data tap
Data tape
Data target
Data task
Data taste
Data tax
Data taxpayer
Data tea
Data teach
Data teacher
Data teaching
Data team
Data tear
Data teaspoon
Data technical
Data technique
Data technology
Data teen
Data teenager
Data telephone
Data telescope
Data television
Data tell
Data temperature
Data temporary
Data ten
Data tend
Data tendency
Data tennis
Data tension
Data tent
Data term
Data terms
Data terrible
Data territory
Data terror
Data terrorism
Data terrorist
Data test
Data testify
Data testimony
Data testing
Data text
Data than
Data thank
Data thanks
Data that
Data the
Data theater
Data their
Data them
Data theme
Data themselves
Data then
Data theory
Data therapy
Data there
Data therefore
Data these
Data they
Data thick
Data thin
Data thing
Data think
Data thinking
Data third
Data thirty
Data this
Data those
Data though
Data thought
Data thousand
Data threat
Data threaten
Data three
Data throat
Data through
Data throughout
Data throw
Data thus
Data ticket
Data tie
Data tight
Data time
Data tiny
Data tip
Data tire
Data tired
Data tissue
Data title
Data to
Data tobacco
Data today
Data toe
Data together
Data tomato
Data tomorrow
Data tone
Data tongue
Data tonight
Data too
Data tool
Data tooth
Data top
Data topic
Data toss
Data total
Data totally
Data touch
Data tough
Data tour
Data tourist
Data tournament
Data toward
Data towards
Data tower
Data town
Data toy
Data trace
Data track
Data trade
Data tradition
Data traditional
Data traffic
Data tragedy
Data trail
Data train
Data training
Data transfer
Data transform
Data transformation
Data transition
Data translate
Data transportation
Data travel
Data treat
Data treatment
Data treaty
Data tree
Data tremendous
Data trend
Data trial
Data tribe
Data trick
Data trip
Data troop
Data trouble
Data truck
Data true
Data truly
Data trust
Data truth
Data try
Data tube
Data tunnel
Data turn
Data TV
Data twelve
Data twenty
Data twice
Data twin
Data two
Data type
Data typical
Data typically
Data ugly
Data ultimate
Data ultimately
Data unable
Data uncle
Data under
Data undergo
Data understand
Data understanding
Data unfortunately
Data uniform
Data union
Data unique
Data unit
Data United
Data universal
Data universe
Data university
Data unknown
Data unless
Data unlike
Data unlikely
Data until
Data unusual
Data up
Data upon
Data upper
Data urban
Data urge
Data us
Data use
Data used
Data useful
Data user
Data usual
Data usually
Data utility
Data vacation
Data valley
Data valuable
Data value
Data variable
Data variation
Data variety
Data various
Data vary
Data vast
Data vegetable
Data vehicle
Data venture
Data version
Data versus
Data very
Data vessel
Data veteran
Data via
Data victim
Data victory
Data video
Data view
Data viewer
Data village
Data violate
Data violation
Data violence
Data violent
Data virtually
Data virtue
Data virus
Data visible
Data vision
Data visit
Data visitor
Data visual
Data vital
Data voice
Data volume
Data volunteer
Data vote
Data voter
Data vs
Data vulnerable
Data wage
Data wait
Data wake
Data walk
Data wall
Data wander
Data want
Data war
Data warm
Data warn
Data warning
Data wash
Data waste
Data watch
Data water
Data wave
Data way
Data we
Data weak
Data wealth
Data wealthy
Data weapon
Data wear
Data weather
Data wedding
Data week
Data weekend
Data weekly
Data weigh
Data weight
Data welcome
Data welfare
Data well
Data west
Data western
Data wet
Data what
Data whatever
Data wheel
Data when
Data whenever
Data where
Data whereas
Data whether
Data which
Data while
Data whisper
Data white
Data who
Data whole
Data whom
Data whose
Data why
Data wide
Data widely
Data widespread
Data wife
Data wild
Data will
Data willing
Data win
Data wind
Data window
Data wine
Data wing
Data winner
Data winter
Data wipe
Data wire
Data wisdom
Data wise
Data wish
Data with
Data withdraw
Data within
Data without
Data witness
Data woman
Data wonder
Data wonderful
Data wood
Data wooden
Data word
Data work
Data worker
Data working
Data works
Data workshop
Data world
Data worried
Data worry
Data worth
Data would
Data wound
Data wrap
Data write
Data writer
Data writing
Data wrong
Data yard
Data yeah
Data year
Data yell
Data yellow
Data yes
Data yesterday
Data yet
Data yield
Data you
Data young
Data your
Data yours
Data yourself
Data youth
Data zone
Function GetMax_OffsetX ()
    m = 1
    For I = 1 To MaxWords
        If Len(LoadedWords(I).Word) Then If LoadedWords(I).X + Len(LoadedWords(I).Word) * _FontWidth > LoadedWords(m).X + Len(LoadedWords(m).Word) * _FontWidth Then m = I
    Next I
    GetMax_OffsetX = m
End Function
Function GetMin_Length ()
    m = 1
    For I = 1 To MaxWords
        If InRange(0, Len(LoadedWords(I).Word), Len(LoadedWords(m).Word)) Then m = I
    Next I
    GetMin_Length = m
End Function
Function InRange (A, B, C)
    If A < B And B < C Then InRange = -1
End Function
